#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

#include <filament/Engine.h>

#include <gltfio/AssetLoader.h>
#include <gltfio/MaterialProvider.h>
#include <gltfio/ResourceLoader.h>

// Generated by the Filament build (see repro/build.sh include paths + link to libuberarchive.a).
#include <uberarchive.h>

namespace {

std::vector<uint8_t> readFile(const char* path) {
    std::ifstream file(path, std::ios::binary);
    if (!file) {
        return {};
    }
    return std::vector<uint8_t>(std::istreambuf_iterator<char>(file), {});
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::fprintf(stderr, "Usage: %s <file.glb|file.gltf>\n", argv[0]);
        return 2;
    }

    const char* gltfPath = argv[1];
    std::vector<uint8_t> gltfBytes = readFile(gltfPath);
    if (gltfBytes.empty()) {
        std::fprintf(stderr, "Failed to read: %s\n", gltfPath);
        return 1;
    }

    filament::Engine* engine = filament::Engine::create(filament::Engine::Backend::NOOP);
    if (!engine) {
        std::fprintf(stderr, "Engine::create(NOOP) failed\n");
        return 1;
    }

    filament::gltfio::MaterialProvider* materials =
            filament::gltfio::createUbershaderProvider(engine, UBERARCHIVE_DEFAULT_DATA,
                    UBERARCHIVE_DEFAULT_SIZE);
    if (!materials) {
        std::fprintf(stderr, "createUbershaderProvider failed\n");
        filament::Engine::destroy(&engine);
        return 1;
    }

    filament::gltfio::AssetConfiguration assetConfig{engine, materials};
    filament::gltfio::AssetLoader* loader = filament::gltfio::AssetLoader::create(assetConfig);
    if (!loader) {
        std::fprintf(stderr, "AssetLoader::create failed\n");
        materials->destroyMaterials();
        delete materials;
        filament::Engine::destroy(&engine);
        return 1;
    }

    filament::gltfio::FilamentAsset* asset = loader->createAsset(gltfBytes.data(),
            static_cast<uint32_t>(gltfBytes.size()));
    if (!asset) {
        std::fprintf(stderr, "AssetLoader::createAsset failed\n");
        filament::gltfio::AssetLoader::destroy(&loader);
        materials->destroyMaterials();
        delete materials;
        filament::Engine::destroy(&engine);
        return 1;
    }

    filament::gltfio::ResourceConfiguration resourceConfig{engine, gltfPath, false};
    filament::gltfio::ResourceLoader resourceLoader(resourceConfig);

    // Triggers meshopt decompression in ResourceLoader, which calls:
    //   filament::gltfio::utility::decodeMeshoptCompression()
    // and hits the unchecked malloc(count * stride).
    (void) resourceLoader.loadResources(asset);

    loader->destroyAsset(asset);
    filament::gltfio::AssetLoader::destroy(&loader);
    materials->destroyMaterials();
    delete materials;
    filament::Engine::destroy(&engine);
    return 0;
}
